## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
notifications:
  email: false
git:
  depth: 99999999
before-install:
  - sudo apt-get install curl
script:
  - julia -e 'Pkg.clone(pwd());'
  - julia -e 'Pkg.build("Mosek");'
