## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
git:
  depth: 99999999
before-install:
  - sudo apt-get install curl
script:
  - julia -e 'Pkg.clone(pwd());'
  - julia -e 'Pkg.build("Mosek");'

#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Mosek"); Pkg.test("Mosek"; coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Mosek")); include(joinpath("docs", "make.jl"))'
